// SPDX-FileCopyrightText: © 2026 The Nile Developers
// SPDX-License-Identifier: GPL-3.0-only

//! Nile ─ Direct, function-based compositor control for River.
//!
//! # Overview
//! Nile replaces River's custom Wayland protocols (`river-window-management-v1`,
//! `river-xkb-bindings-v1`, `river-layer-shell-v1`, `river-input-management-v1`,
//! `river-libinput-config-v1`, `river-xkb-config-v1`) with ordinary Zig functions.
//!
//! Instead of an out-of-process window manager that speaks Wayland, you link
//! Nile as a library (or write a config script that imports it) and manipulate
//! compositor state directly. No `wl_global`, no `manage_start` / `render_finish`
//! dance - just call a function and the compositor applies the change on the
//! next transaction.
//!
//! ## Design principles
//! * **Functions, not protocols.** Every operation that previously required a
//!   `river_*_v1` request is now a Zig function with typed arguments and
//!   `error` returns.
//! * **Synchronous intent, asynchronous commit.** Mutations are recorded
//!   immediately and flushed atomically at the next `commit()` / idle. This
//!   preserves frame perfection of the original transaction system while giving
//!   callers a familiar imperative API.
//! * **No hidden globals.** All state lives in `Server` (`@import("main.zig").server`).
//!   The API is a thin, documented façade over `Window`, `Output`, `Seat`, etc.
//! * **Backwards-compat shim.** The old protocol globals are still generated by
//!   `build.zig` but **not advertised** unless `Nile.enableLegacyProtocols` is
//!   set. New code should not use them.
//!
//! ## Quick start
//! ```zig
//! const Nile = @import("Nile.zig");
//!
//! // Focus a window
//! try Nile.Seat.focusWindow(seat, window);
//!
//! // Tile windows: give each half the output
//! const out = Nile.Output.primary() orelse return;
//! const wins = Nile.Window.list();
//! for (wins, 0..) |w, i| {
//!     const x: i32 = if (i % 2 == 0) out.x else out.x + @divTrunc(out.width, 2);
//!     Nile.Window.setPosition(w, x, out.y);
//!     Nile.Window.setDimensions(w, @divTrunc(out.width, 2), out.height);
//! }
//! Nile.commit();
//! ```
//!
//! See `doc/nile-api.md` for a complete guide.

const std = @import("std");
const assert = std.debug.assert;
const wlr = @import("wlroots");
const wl = @import("wayland").server.wl;
const xkb = @import("xkbcommon");

const server = &@import("main.zig").server;
const util = @import("util.zig");
const Workspace = @import("Workspace.zig");
const WindowMod = @import("Window.zig");
const OutputMod = @import("Output.zig");
const SeatMod = @import("Seat.zig");
const InputDevice = @import("InputDevice.zig");
const XkbBinding = @import("XkbBinding.zig");
pub const Compositor = @import("Compositor.zig");
pub const Animation = @import("Animation.zig");

// ---------------------------------------------------------------------------
// Top-level controls
// ---------------------------------------------------------------------------

/// If true, re-advertise the legacy `river_*_v1` globals for compatibility
/// with old external window managers. Default `false` - Nile is function-only.
pub var enableLegacyProtocols: bool = false;

/// Request that the compositor re-evaluates windowing state on the next idle.
/// Equivalent to the old `river_window_manager_v1.manage_dirty` request, but
/// as a plain function. Safe to call from any thread that holds the Wayland
/// event loop lock (i.e. the main thread).
pub fn dirtyWindowing() void {
    server.wm.dirtyWindowing();
}

/// Lazy variant - schedules a manage sequence without blocking input.
/// Mirrors `dirtyWindowingLazy`.
pub fn dirtyWindowingLazy() void {
    server.wm.dirtyWindowingLazy();
}

/// Mark rendering state dirty (position, stacking order, borders, clip boxes).
pub fn dirtyRendering() void {
    server.wm.dirtyRendering();
}

/// Immediate variant — apply pending rendering state to the scene graph
/// synchronously without waiting for the next idle. Use from
/// `onPointerMotion` for move/drag to achieve per-wayland-call latency.
/// Only rendering state is flushed; windowing (dimensions/configure) still
/// goes through `dirtyWindowing`/`dirtyWindowingLazy`.
pub fn dirtyRenderingImmediate() void {
    server.wm.dirtyRenderingImmediate();
}

/// Animation controls — see `Animation.zig` for kinds, durations and JSON.
/// Example: `Nile.setAnimationConfig(Animation.Config.disabled())` to disable all.
pub fn setAnimationConfig(config: Animation.Config) void {
    Animation.set(config);
}
pub fn getAnimationConfig() Animation.Config {
    return Animation.get();
}
pub fn disableAllAnimations() void {
    Animation.disableAll();
}
/// Load animation config from JSON file (e.g. `~/.config/nile/animations.json`).
/// Missing file → keep defaults. Unknown fields are ignored for forward compat.
pub fn loadAnimationConfigFromFile(path: []const u8) !void {
    const cfg = try Animation.Config.loadFromFile(std.heap.page_allocator, path);
    Animation.set(cfg);
}
/// Load from XDG config home (`$XDG_CONFIG_HOME/nile/animations.json` or `~/.config/nile/animations.json`).
pub fn loadAnimationConfigFromXdg() void {
    _ = Animation.loadGlobalFromXdg(std.heap.page_allocator);
}

/// Terminate the Wayland session. Equivalent to `river_window_manager_v1.exit_session`.
pub fn exitSession() void {
    server.wl_server.terminate();
}

/// The struct that controls all compositor behavior. See `Compositor.zig`.
/// Register your implementation before the first window appears:
/// `Nile.setCompositor(Compositor.initCompositor(MyCompositor, &my_instance))`
pub fn setCompositor(compositor: Compositor.Compositor) void {
    Compositor.set(compositor);
}

pub fn clearCompositor() void {
    Compositor.clear();
}

pub const Event = Compositor.Event;

// ---------------------------------------------------------------------------
// Window API — replaces `river_window_v1`
// ---------------------------------------------------------------------------

pub const WindowApi = struct {
    /// Return a slice of all currently known windows (including unmapped).
    /// The slice is valid until the next window create/destroy.
    /// Caller must not free the slice; iterate directly via `server.wm.windows`.
    pub fn count() usize {
        var n: usize = 0;
        var it = server.wm.windows.iterator();
        while (it.next()) |_| n += 1;
        return n;
    }

    /// Iterate windows. Example:
    /// ```zig
    /// var it = Nile.Window.iter();
    /// while (it.next()) |win| { ... }
    /// ```
    pub fn iter() @import("slotmap").SlotMap(*WindowMod).Iterator {
        return server.wm.windows.iterator();
    }

    /// Get window by its stable `Ref` (survives across transactions).
    pub fn get(ref: WindowMod.Ref) ?*WindowMod {
        return ref.get();
    }

    /// Close the window. The client may ignore the request (e.g. show a save dialog).
    /// Always succeeds from the compositor side; the actual destruction is async.
    pub fn close(window: *WindowMod) void {
        window.wm_requested.close = true;
        server.wm.dirtyWindowing();
    }

    /// Propose new content dimensions for the window.
    /// `width`/`height` of 0 means "let the client choose".
    /// This mutates `wm_requested.dimensions` and dirties windowing state.
    /// `animate` true means visual size change is interpolated (200ms) at
    /// river layer; false means immediate. Grabbed windows are always immediate
    /// regardless of flag to avoid input lag.
    pub fn setDimensions(window: *WindowMod, width: u31, height: u31, animate: bool) void {
        window.wm_requested.dimensions = .{ .width = width, .height = height };
        // Visual size animation — batch with position if also animating same frame
        if (animate and window.state == .mapped) {
            window.startSizeAnimation(@intCast(width), @intCast(height), true);
        } else {
            window.startSizeAnimation(@intCast(width), @intCast(height), false);
        }
        server.wm.dirtyWindowing();
    }

    /// Convenience: set width/height with i32 args (negative values rejected).
    pub fn setDimensionsChecked(window: *WindowMod, width: i32, height: i32, animate: bool) error{InvalidDimensions}!void {
        if (width < 0 or height < 0) return error.InvalidDimensions;
        window.wm_requested.dimensions = .{ .width = @intCast(width), .height = @intCast(height) };
        if (animate and window.state == .mapped) {
            window.startSizeAnimation(width, height, true);
        } else {
            window.startSizeAnimation(width, height, false);
        }
        server.wm.dirtyWindowing();
    }

    /// Backwards-compat wrapper without animation flag (defaults to animate=true).
    pub fn setDimensionsNoAnim(window: *WindowMod, width: u31, height: u31) void {
        setDimensions(window, width, height, true);
    }

    /// Set the window's position in global compositor space (rendering state).
    /// `animate` true interpolates at river layer (200ms easeOutCubic), false
    /// applies immediately. Grabbed windows (seat.op.window) are forced immediate
    /// even if animate=true to prevent cursor lag. Batched: rapid pos+size changes
    /// in same arrange are coalesced into one animation from current visual to
    /// final target.
    pub fn setPosition(window: *WindowMod, x: i32, y: i32, animate: bool) void {
        window.rendering_requested.x = x;
        window.rendering_requested.y = y;
        if (animate) {
            window.startPosAnimation(x, y, true);
            // Animation drives visual; still need to ensure frame is scheduled.
            // Timer will tick, but also mark rendering dirty for final commit.
            server.wm.dirtyRendering();
        } else {
            window.startPosAnimation(x, y, false);
            server.wm.dirtyRendering();
        }
    }

    /// Immediate variant — update scene graph synchronously without waiting
    /// for idle. Use for per-motion drag/move. Still records
    /// `rendering_requested` but also applies `box` + `wlr_scene_tree`
    /// position now, so next frame shows new position without a
    /// `dirtyRendering` idle round-trip. Always animate=false.
    pub fn setPositionImmediate(window: *WindowMod, x: i32, y: i32) void {
        window.rendering_requested.x = x;
        window.rendering_requested.y = y;
        window.startPosAnimation(x, y, false);
        window.applyRenderingImmediate();
        // Clear any pending rendering dirty since we flushed it.
        if (server.wm.rendering_scheduled.dirty) {
            server.wm.cleanRendering();
        }
    }

    /// Hide the window (and its borders/decorations). No-op if already hidden.
    pub fn hide(window: *WindowMod) void {
        window.rendering_requested.hidden = true;
        server.wm.dirtyRendering();
    }

    /// Show a previously hidden window.
    pub fn show(window: *WindowMod) void {
        window.rendering_requested.hidden = false;
        server.wm.dirtyRendering();
    }

    /// Whether the window is currently hidden.
    pub fn isHidden(window: *WindowMod) bool {
        return window.rendering_requested.hidden;
    }

    /// Tell the client to use server-side decoration (SSD) or client-side (CSD).
    pub fn setSsd(window: *WindowMod, ssd: bool) void {
        window.wm_requested.ssd = ssd;
        server.wm.dirtyWindowing();
    }

    /// Inform the window of its tiled edges (affects CSD - e.g. shadows).
    /// `edges` is a bitset of `.top | .bottom | .left | .right` or `.none`.
    pub fn setTiled(window: *WindowMod, edges: anytype) void {
        window.wm_requested.tiled = edges;
        server.wm.dirtyWindowing();
    }

    /// Set which capabilities to advertise to the window (window_menu, maximize, fullscreen, minimize).
    pub fn setCapabilities(window: *WindowMod, caps: WindowMod.Configure) void {
        _ = window;
        _ = caps;
        // Caller can set individual fields via wm_requested.capabilities directly if needed.
        // Provided for symmetry with protocol's set_capabilities.
        server.wm.dirtyWindowing();
    }

    /// Set window borders (rendering state). Pass `edges = .{}` or `width=0` to disable.
    pub fn setBorders(window: *WindowMod, edges: anytype, width: u31, r: u32, g: u32, b: u32, a: u32) void {
        window.rendering_requested.border = .{
            .edges = edges,
            .width = width,
            .r = r,
            .g = g,
            .b = b,
            .a = a,
        };
        server.wm.dirtyRendering();
    }

    /// Clip window + borders + decorations to `box` in window-local coordinates.
    /// Zero width/height disables clipping.
    pub fn setClipBox(window: *WindowMod, clip_box: wlr.Box) void {
        window.rendering_requested.clip = clip_box;
        server.wm.dirtyRendering();
    }

    /// Clip only window content (excluding borders/decorations).
    pub fn setContentClipBox(window: *WindowMod, clip_box: wlr.Box) void {
        window.rendering_requested.content_clip = clip_box;
        server.wm.dirtyRendering();
    }

    /// Make window fullscreen on `output`. Pass null to exit fullscreen.
    pub fn setFullscreen(window: *WindowMod, output: ?*OutputMod) void {
        window.wm_requested.fullscreen = output;
        server.wm.dirtyWindowing();
    }

    /// Convenience: toggle fullscreen.
    pub fn toggleFullscreen(window: *WindowMod, output: *OutputMod) void {
        if (window.wm_requested.fullscreen != null) {
            window.wm_requested.fullscreen = null;
        } else {
            window.wm_requested.fullscreen = output;
        }
        server.wm.dirtyWindowing();
    }

    /// Inform window of fullscreen state for decoration purposes (CSD).
    pub fn setInformFullscreen(window: *WindowMod, fullscreen: bool) void {
        window.wm_requested.inform_fullscreen = fullscreen;
        server.wm.dirtyWindowing();
    }

    /// Inform window it is being interactively resized (affects resize look).
    pub fn setResizing(window: *WindowMod, resizing: bool) void {
        window.wm_requested.resizing = resizing;
        server.wm.dirtyWindowing();
    }

    /// Inform window it is maximized / unmaximized.
    pub fn setMaximized(window: *WindowMod, maximized: bool) void {
        window.wm_requested.maximized = maximized;
        server.wm.dirtyWindowing();
    }

    /// Recommend maximum dimensions to the window (configure_bounds hint).
    pub fn setBounds(window: *WindowMod, max_width: u31, max_height: u31) void {
        window.wm_requested.bounds = .{ .width = max_width, .height = max_height };
        server.wm.dirtyWindowing();
    }

    /// Move window to top of stacking order (last in `rendering_requested` list).
    pub fn raiseToTop(window: *WindowMod) void {
        window.node.link.remove();
        server.wm.rendering_requested.list.append(&window.node);
        server.wm.dirtyRendering();
    }

    /// Focus this window on its seat (uses default seat if none specified).
    pub fn focus(window: *WindowMod) void {
        const seat = server.input_manager.defaultSeat();
        seat.wm_requested.focus = .{ .window = window.ref };
        server.wm.dirtyWindowing();
    }

    /// Accessors for read-only window properties.
    pub fn title(window: *WindowMod) ?[*:0]const u8 {
        return window.getTitle();
    }
    pub fn appId(window: *WindowMod) ?[*:0]const u8 {
        return window.getAppId();
    }
    pub fn box(window: *WindowMod) wlr.Box {
        return window.box;
    }
};

pub const WindowNamespace = WindowApi;

// ---------------------------------------------------------------------------
// Output API — replaces `river_output_v1`
// ---------------------------------------------------------------------------

pub const OutputApi = struct {
    /// Iterate all outputs with a backing `wlr_output`.
    pub fn iter() wl.list.Head(OutputMod, .link).Iterator(.forward) {
        return server.om.outputs.iterator(.forward);
    }

    /// Find output by name (e.g. "DP-1").
    pub fn byName(name: []const u8) ?*OutputMod {
        var it = server.om.outputs.iterator(.forward);
        while (it.next()) |o| {
            if (o.wlr_output) |w| if (std.mem.eql(u8, std.mem.sliceTo(w.name, 0), name)) return o;
        }
        return null;
    }

    /// Primary output = first in list (convenience).
    pub fn primary() ?*OutputMod {
        return server.om.outputs.first();
    }

    /// Set output position in global layout (requires `dirtyWindowing` flush).
    pub fn setPosition(output: *OutputMod, x: i32, y: i32) void {
        output.scheduled.x = x;
        output.scheduled.y = y;
        output.scheduled.auto_layout = false;
        server.wm.dirtyWindowing();
    }

    /// Set scale factor (e.g. 1.0, 1.25, 2.0).
    pub fn setScale(output: *OutputMod, scale: f32) void {
        output.scheduled.scale = @round(scale * 120) / 120;
        server.wm.dirtyWindowing();
    }

    /// Set transform (rotation / flip).
    pub fn setTransform(output: *OutputMod, transform: wl.Output.Transform) void {
        output.scheduled.transform = transform;
        server.wm.dirtyWindowing();
    }

    /// Enable / disable output power (DPMS). True = on.
    pub fn setEnabled(output: *OutputMod, enabled: bool) void {
        output.scheduled.state = if (enabled) .enabled else .disabled_hard;
        server.wm.dirtyWindowing();
    }

    /// Whether tearing (async page flip) is allowed on this output.
    pub fn setTearing(output: *OutputMod, tearing: bool) void {
        output.rendering_requested.tearing = tearing;
        server.wm.dirtyRendering();
    }

    /// Re-run automatic layout for outputs marked `auto_layout`.
    pub fn autoLayout() void {
        server.om.autoLayout();
        server.wm.dirtyWindowing();
    }

    /// Read current (committed) output box in global coords.
    pub fn currentBox(output: *OutputMod) wlr.Box {
        return output.current.box();
    }

    /// Effective box — prefers `current` but falls back to `sent`/`scheduled`
    /// when the output hasn't committed its initial modeset yet (width/height == 0).
    /// Useful for early window placement before the first `commitOutputState`.
    pub fn effectiveBox(output: *OutputMod) wlr.Box {
        const cur = output.current.box();
        if (cur.width != 0 and cur.height != 0) return cur;
        const sent = output.sent.box();
        if (sent.width != 0 and sent.height != 0) return sent;
        return output.scheduled.box();
    }
};

// ---------------------------------------------------------------------------
// Seat API — replaces `river_seat_v1`
// ---------------------------------------------------------------------------

pub const SeatApi = struct {
    /// Iterate all seats.
    pub fn iter() wl.list.Head(SeatMod, .link).Iterator(.forward) {
        return server.input_manager.seats.iterator(.forward);
    }

    /// Find seat by name.
    pub fn byName(name: []const u8) ?*SeatMod {
        var it = server.input_manager.seats.iterator(.forward);
        while (it.next()) |s| if (std.mem.eql(u8, std.mem.sliceTo(s.wlr_seat.name, 0), name)) return s;
        return null;
    }

    /// Default seat (always exists, name "default").
    pub fn default() *SeatMod {
        return server.input_manager.defaultSeat();
    }

    /// Create a new seat. No-op if name already exists.
    pub fn create(name: [:0]const u8) !void {
        var it = server.input_manager.seats.iterator(.forward);
        while (it.next()) |s| if (std.mem.orderZ(u8, name, s.wlr_seat.name) == .eq) return;
        try SeatMod.create(name);
    }

    /// Destroy a seat by name (cannot destroy "default").
    pub fn destroy(name: []const u8) void {
        if (std.mem.eql(u8, name, "default")) return;
        var it = server.input_manager.seats.iterator(.forward);
        _ = it.next(); // skip default
        while (it.next()) |s| if (std.mem.eql(u8, std.mem.sliceTo(s.wlr_seat.name, 0), name)) {
            s.destroying = true;
            server.wm.dirtyWindowing();
            break;
        };
    }

    /// Focus a window on `seat`.
    pub fn focusWindow(seat: *SeatMod, window: *WindowMod) void {
        seat.wm_requested.focus = .{ .window = window.ref };
        server.wm.dirtyWindowing();
    }

    /// Clear focus on `seat`.
    pub fn clearFocus(seat: *SeatMod) void {
        seat.wm_requested.focus = .clear;
        server.wm.dirtyWindowing();
    }

    /// Focus a shell surface (e.g. layer surface) — rarely needed, use layer API.
    pub fn focusShellSurface(seat: *SeatMod, shell_surface: anytype) void {
        _ = shell_surface;
        _ = seat;
        // Stub: wire to shell surface type when available
        server.wm.dirtyWindowing();
    }

    /// Warp pointer to absolute compositor coordinates.
    pub fn warpPointer(seat: *SeatMod, x: i32, y: i32) void {
        seat.wm_requested.pointer_warp = .{ .x = x, .y = y };
        server.wm.dirtyWindowing();
    }

    /// Start an interactive pointer operation (move). Window manager would then
    /// track pointer motion and call `Window.setPosition` each frame.
    /// Deprecated: use `opStartMove`/`opStartResize` or handle `pointer_button`
    /// events directly. This now starts a move-kind op.
    pub fn opStartPointer(seat: *SeatMod) void {
        startOpImmediate(seat, .move, .{}, null);
    }

    /// Start an interactive move for `window` on `seat`. Compositor should
    /// call this after receiving a `pointer_button` with `kind == .normal`
    /// when it decides the hold should become a move (e.g. Mod+drag).
    pub fn opStartMove(seat: *SeatMod, window: ?*WindowMod) void {
        startOpImmediate(seat, .move, .{}, window);
    }

    /// Start an interactive resize for `window` on `seat`.
    pub fn opStartResize(seat: *SeatMod, window: ?*WindowMod, edges: WindowMod.Edges) void {
        startOpImmediate(seat, .resize, edges, window);
    }

    /// End current seat operation.
    pub fn opEnd(seat: *SeatMod) void {
        // End immediately if op exists, otherwise queue for next manage.
        // Immediate path also clears any pending start_pointer so manageFinish
        // does not recreate the op after we already ended it.
        if (seat.op != null) {
            seat.opEnd();
            seat.wm_requested.op = .none;
        } else {
            // If a start was pending but never committed, cancel it
            switch (seat.wm_requested.op) {
                .start_pointer => seat.wm_requested.op = .none,
                else => seat.wm_requested.op = .end,
            }
            server.wm.dirtyWindowing();
        }
    }

    fn startOpImmediate(seat: *SeatMod, kind: @import("Compositor.zig").PointerButtonKind, edges: WindowMod.Edges, window: ?*WindowMod) void {
        // Create op synchronously so the subsequent pointer_button released
        // sees seat.op != null even if release arrives before next manage
        // (race that previously caused "no move released event").
        if (seat.op == null) {
            const win_x: i32, const win_y: i32, const win_w: u31, const win_h: u31 = if (window) |win|
                .{ win.box.x, win.box.y, @intCast(@max(0, win.box.width)), @intCast(@max(0, win.box.height)) }
            else
                .{ 0, 0, 0, 0 };
            seat.op = .{
                .input = .pointer,
                .start_x = @intFromFloat(seat.cursor.wlr_cursor.x),
                .start_y = @intFromFloat(seat.cursor.wlr_cursor.y),
                .x = @intFromFloat(seat.cursor.wlr_cursor.x),
                .y = @intFromFloat(seat.cursor.wlr_cursor.y),
                .kind = kind,
                .edges = edges,
                .window = if (window) |w| w.ref else null,
                .win_x = win_x,
                .win_y = win_y,
                .win_width = win_w,
                .win_height = win_h,
            };
            seat.cursor.opStartPointer();
        }
        // Also queue via wm_requested for consistency; manageFinish will see op != null and skip duplicate creation
        seat.wm_requested.op = .{ .start_pointer = .{ .kind = kind, .edges = edges, .window = if (window) |w| w.ref else null } };
        server.wm.dirtyWindowing();
    }

    /// Get current pointer position.
    pub fn pointerPos(seat: *SeatMod) struct { x: f64, y: f64 } {
        return .{ .x = seat.cursor.wlr_cursor.x, .y = seat.cursor.wlr_cursor.y };
    }

    /// Set xcursor theme. `name` may be null to use default.
    pub fn setXcursorTheme(seat: *SeatMod, name: ?[*:0]const u8, size: u32) !void {
        try seat.cursor.setTheme(name, size);
    }

    /// Create a key binding on `seat`. Returns the binding handle.
    /// `modifiers` is a bitset of `wlr.Keyboard.ModifierMask` (u32).
    /// `keysym` is an xkbcommon keysym (e.g. `xkb.Keysym.fromName("Return")`).
    pub fn addXkbBinding(seat: *SeatMod, keysym: xkb.Keysym, modifiers: anytype) !*XkbBinding {
        const mods: u32 = switch (@typeInfo(@TypeOf(modifiers))) {
            .int, .comptime_int => @intCast(modifiers),
            else => @bitCast(@as(wlr.Keyboard.ModifierMask, modifiers)),
        };
        const binding = try XkbBinding.create(seat, keysym, mods);
        binding.wm_requested.enabled = true;
        return binding;
    }

    /// Remove all bindings matching keysym+modifiers.
    pub fn removeXkbBinding(seat: *SeatMod, keysym: xkb.Keysym, modifiers: anytype) void {
        const mods: u32 = switch (@typeInfo(@TypeOf(modifiers))) {
            .int, .comptime_int => @intCast(modifiers),
            else => @bitCast(@as(wlr.Keyboard.ModifierMask, modifiers)),
        };
        var it = seat.xkb_bindings.safeIterator(.forward);
        while (it.next()) |binding| {
            if (binding.keysym == keysym and binding.modifiers == mods) {
                binding.destroy();
            }
        }
    }
};

// ---------------------------------------------------------------------------
// Input API — replaces `river_input_manager_v1` / `river_input_device_v1`
// ---------------------------------------------------------------------------

pub const Input = struct {
    /// Iterate all input devices.
    pub fn iter() wl.list.Head(InputDevice, .link).Iterator(.forward) {
        return server.input_manager.devices.iterator(.forward);
    }

    /// Find device by name.
    pub fn byName(name: []const u8) ?*InputDevice {
        var it = server.input_manager.devices.iterator(.forward);
        while (it.next()) |d| if (std.mem.eql(u8, std.mem.sliceTo(d.wlr_device.name, 0), name)) return d;
        return null;
    }

    /// Assign device to seat by name. No-op if seat doesn't exist.
    pub fn assignToSeat(device: *InputDevice, seat_name: []const u8) void {
        var it = server.input_manager.seats.iterator(.forward);
        while (it.next()) |s| if (std.mem.eql(u8, std.mem.sliceTo(s.wlr_seat.name, 0), seat_name)) {
            device.assignToSeat(s);
            return;
        };
    }

    /// Set keyboard repeat rate (keys per second) and delay (ms).
    pub fn setRepeat(device: *InputDevice, rate: i32, delay: i32) error{InvalidRate}!void {
        if (rate < 0 or delay < 0) return error.InvalidRate;
        if (device.wlr_device.type != .keyboard) return;
        const kbd: *@import("Keyboard.zig") = @ptrCast(@alignCast(device.wlr_device.data));
        kbd.setRepeatInfo(@intCast(rate), @intCast(delay));
    }

    /// Set scroll factor for pointer devices.
    pub fn setScrollFactor(device: *InputDevice, factor: f64) error{InvalidFactor}!void {
        if (factor < 0) return error.InvalidFactor;
        if (device.wlr_device.type != .pointer) return;
        device.config.scroll_factor = @floatCast(factor);
    }

    /// Map pointer/touch/tablet device to output.
    pub fn mapToOutput(device: *InputDevice, output: ?*wlr.OutputMod) void {
        if (device.wlr_device.type != .pointer and
            device.wlr_device.type != .touch and
            device.wlr_device.type != .tablet) return;
        device.config.map_to_output = output;
        if (device.wlr_device.type == .touch or device.wlr_device.type == .tablet) {
            device.seat.cursor.wlr_cursor.mapInputToOutput(device.wlr_device, output);
        }
    }

    /// Map device to rectangle in global compositor space.
    pub fn mapToRectangle(device: *InputDevice, rect: ?wlr.Box) error{InvalidRectangle}!void {
        if (rect) |r| if (r.width < 0 or r.height < 0) return error.InvalidRectangle;
        if (device.wlr_device.type != .pointer and
            device.wlr_device.type != .touch and
            device.wlr_device.type != .tablet) return;
        if (rect) |r| {
            device.config.map_to_rectangle = r;
            device.config.map_to_output = null;
            if (device.wlr_device.type == .touch or device.wlr_device.type == .tablet) {
                device.seat.cursor.wlr_cursor.mapInputToRegion(device.wlr_device, &r);
            }
        } else {
            device.config.map_to_rectangle = .{ .x = 0, .y = 0, .width = 0, .height = 0 };
            if (device.wlr_device.type == .touch or device.wlr_device.type == .tablet) {
                device.seat.cursor.wlr_cursor.mapInputToRegion(device.wlr_device, null);
            }
        }
    }
};

// ---------------------------------------------------------------------------
// Layer shell API — replaces `river_layer_shell_v1`
// ---------------------------------------------------------------------------

pub const Layer = struct {
    /// Set the default output for new layer surfaces that don't request one.
    pub fn setDefaultOutput(output: *OutputMod) void {
        var it = server.om.outputs.iterator(.forward);
        while (it.next()) |o| o.layer_shell.requested.default = false;
        output.layer_shell.requested.default = true;
        server.wm.dirtyWindowing();
    }

    /// Get non-exclusive area for an output (area left after exclusive zones).
    pub fn nonExclusiveArea(output: *OutputMod) wlr.Box {
        return output.layer_shell.scheduled.non_exclusive_area;
    }
};

// ---------------------------------------------------------------------------
// Workspace API — replaces `river_workspace_v1`
// ---------------------------------------------------------------------------

pub const WorkspaceApi = struct {
    /// Workspace info returned by listWorkspaces and getWorkspace.
    pub const Info = Workspace.Info;

    /// Switch to the workspace with the given id.
    pub fn switchWorkspace(id: u64) !u64 {
        return server.workspace.switchWorkspace(id);
    }

    /// Return the id of the current workspace.
    pub fn currentWorkspace() u64 {
        return server.workspace.currentWorkspace();
    }

    /// Create a new workspace with the given number and name.
    pub fn addWorkspace(number: u64, name: []const u8) !u64 {
        _ = try server.workspace.addWorkspace(util.gpa, number, name);
        return number;
    }

    /// Remove a workspace by id.
    pub fn removeWorkspace(id: u64) !void {
        try server.workspace.removeWorkspace(util.gpa, id);
    }

    /// Rename a workspace. The name is duplicated; the caller keeps its slice.
    pub fn setWorkspaceName(id: u64, name: []const u8) !void {
        try server.workspace.setWorkspaceName(util.gpa, id, name);
    }

    /// List all workspaces.
    pub fn listWorkspaces() ![]Info {
        return server.workspace.listWorkspaces(util.gpa);
    }

    /// Move a window to a different workspace.
    pub fn moveWindowToWorkspace(window: *WindowMod, id: u64) !void {
        try server.workspace.moveWindowToWorkspace(window, id);
    }
};

// Re-export namespaces for ergonomic `Nile.Window`, `Nile.Output`, etc.
pub const WindowNS = WindowApi;
pub const OutputNS = OutputApi;
pub const SeatNS = SeatApi;
// Ergonomic aliases matching docs (`Nile.Window`, `Nile.Output`, `Nile.Seat`)
pub const Window = WindowApi;
pub const Output = OutputApi;
pub const Seat = SeatApi;

// Friendly aliases
pub const window_api = WindowApi;
pub const output_api = OutputApi;
pub const seat_api = SeatApi;
